module Main where

main :: IO ()
main = do
  putStrLn "Hello, Haskell!"
  putStrLn "Welcome"
  putStrLn "Welcome again"
  putStrLn "Welcome 2"
  putStrLn "Welcome 3"
  putStrLn "Welcome 4"
  putStrLn "Welcome 5"
  putStrLn "Welcome 6"
  putStrLn "Welcome 7"
  putStrLn "Welcome 8"
  putStrLn "Welcome 9"
  putStrLn "Welcome 10"
  putStrLn "Welcome 11"
  putStrLn "Welcome 12"
  putStrLn "Welcome 13"
  putStrLn "Welcome 14"
  putStrLn "Welcome"
  putStrLn "Welcome"
  putStrLn "Welcome"
  putStrLn "Welcome"
  putStrLn "Welcome"
  putStrLn "Welcome"
  putStrLn "Welcome"
